nodeLinker: node-modules

npmAuthToken: ffffffff-ffff-ffff-ffff-ffffffffffff

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
