/** @jsxImportSource react */
// Default Import Source for nativewind has known error with Server Components: https://github.com/marklawlor/nativewind/issues/772

import "../global.css";
import { GlobalProvider } from "./providers";

export const metadata = {
  title: "Create Solito App",
  description: "Generated by create Solito app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <GlobalProvider>{children}</GlobalProvider>
      </body>
    </html>
  );
}
