/** @jsxImportSource react */

import "../global.css";
import { StylesProvider } from "./styles-provider";

export const metadata = {
  title: "Create Solito App",
  description: "Generated by create Solito app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <StylesProvider>{children}</StylesProvider>
      </body>
    </html>
  );
}
